spring:
    application:
        name: template
    profiles:
        active: local
    config:
        import:
            - classpath:application-secret.yml

    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect

# application.yml
swagger:
    title: "Koscom hackathon API"
    description: "24시간 주식 정보 분석"
    version: "1.0.0"
    external-docs-description: "프로젝트 API 문서"
