spring:
  config:
    activate:
      on-profile: "local"
    import: classpath:application-secret.yml

  # mysql 데이터 베이스
  datasource:
    url: jdbc:mysql://localhost:3308/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: 3600
  refresh-token-expire-period: 604800

openai:
  api-key: ${OPENAI_API_KEY}

# 네이버 클라우드 CLOVA Voice 설정
naver:
  clova:
    client-id: ${NAVER_CLOVA_CLIENT_ID}
    client-secret: ${NAVER_CLOVA_CLIENT_SECRET}
    api-url: https://naveropenapi.apigw-pub.fin-ntruss.com/tts-premium/v1/tts