spring:
  # mysql 데이터 베이스
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-3p4k04-fkr.cdb.fin-ntruss.com:3306/koscom?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expire-period: 3600
  refresh-token-expire-period: 604800

openai:
  api-key: ${OPENAI_API_KEY}